"""
Litmus TrustLine — Outbound Call Authentication for TVS Credit
================================================================

THE INVERSION
-------------
An OTP makes the CUSTOMER prove identity to the INSTITUTION.
Every voice scam in India exploits exactly that direction:
    "Sir, aapka OTP bataiye."

TrustLine reverses the arrow. The INSTITUTION proves identity to the
CUSTOMER. The code only ever travels outward — TVS Credit issues it,
TVS Credit speaks it, the customer verifies it.

That inversion changes the customer-education message from a rule people
routinely break under pressure:
    "Never share your OTP"
into a rule that is safe even when broken:
    "Always make the caller tell you the TrustLine code."

Leaking a TrustLine phrase teaches an attacker nothing. It is session-bound,
single-use, time-limited and HMAC-keyed to a server secret. A scammer who
overhears one cannot mint another, cannot replay it into a different session,
and cannot use it against a different customer.

WHY THIS SITS ABOVE THE 1600-SERIES MANDATE
-------------------------------------------
TRAI has mandated the 1600-number series for BFSI service and transactional
calls (NBFCs phased in Feb-Mar 2026). That mandate authenticates the NUMBER.
It does not authenticate the HUMAN, it does not cover WhatsApp/OTT calls,
and it does not survive CLI spoofing.

Worse: by training 2.44 crore TVS Credit customers that "1600 == genuinely
TVS", the mandate manufactures a trust signal that is now worth stealing.
TrustLine is a shared-secret challenge rather than an identity display, so
it survives caller-ID spoofing by construction.

WHY THIS DOES NOT DEPEND ON VOICE DETECTION ACCURACY
----------------------------------------------------
Litmus's own measured results: the voice ensemble catches ~35% of 2019-era
TTS and 0% of modern neural TTS. TrustLine was designed around that ceiling,
not in spite of it. A challenge-response code is a possession/knowledge
factor. A perfect voice clone still cannot produce it.

SECURITY PROPERTIES IMPLEMENTED HERE
------------------------------------
  1. Unforgeable      — HMAC-SHA256 under a server-held secret
  2. Session-bound    — phrase binds customer + agent + session + purpose
  3. Time-limited     — TTL, default 10 minutes
  4. Single-use       — verification burns the session
  5. Constant-time    — hmac.compare_digest, no timing oracle
  6. Out-of-band      — delivered on a channel the caller does not control
  7. Fail-loud        — a verification with NO active session is the single
                        strongest scam signal available, and is escalated

FRAUD INTELLIGENCE (the part no KYC vendor can offer)
-----------------------------------------------------
Every failed verification is a scammer revealing themselves in real time.
TrustLine records the claimed purpose, the caller number, and the timing,
and clusters them into live campaign alerts. TVS Credit gets a fraud feed
generated by the attackers themselves.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import secrets
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import fri
import consortium


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# In production this is an HSM / KMS-held key, rotated on a schedule and
# never present in application memory in plaintext. Sourced from env so the
# demo is reproducible without shipping a secret in the repo.
_SERVER_SECRET: bytes = os.environ.get(
    "LITMUS_TRUSTLINE_SECRET", "litmus-demo-secret-do-not-use-in-production"
).encode("utf-8")

SESSION_TTL_SECONDS = 600          # 10 minutes
MAX_VERIFY_ATTEMPTS = 3            # per session, then it locks
CAMPAIGN_ALERT_THRESHOLD = 3       # failed verifications before campaign alert
CAMPAIGN_WINDOW_SECONDS = 3600     # cluster failures within 1 hour

# Who Litmus is inside the TrustLine consortium.
SELF_MEMBER_ID = os.environ.get("LITMUS_CONSORTIUM_MEMBER", "tvs_credit")


# ---------------------------------------------------------------------------
# Phrase alphabet
# ---------------------------------------------------------------------------
#
# Design note: this is deliberately NOT a 6-digit number.
#
# A TVS Credit customer base that is majority semi-urban and rural, speaking
# Hindi and regional languages, verifying a code by EAR on a phone call, over
# a two-wheeler showroom's ambient noise, needs a phrase that survives
# mishearing. Digits fail badly here: Hindi "chhe"(6)/"che" and English
# "five"/"nine" collide constantly on a low-bitrate mobile call.
#
# So: two words + two digits. The words are short, phonetically distant from
# each other, and chosen to be recognisable to a Hindi/English bilingual
# speaker without being English-literacy-dependent. 64 x 64 x 100 = 409,600
# combinations, which is ample for a 10-minute single-use window (an online
# guessing attack gets 3 tries).

_WORDS_A = [
    "TIGER", "MANGO", "RIVER", "TEMPLE", "MONSOON", "COTTON", "SUGAR", "COPPER",
    "GARDEN", "MARBLE", "PEPPER", "SILVER", "JUNGLE", "CAMEL", "LOTUS", "MASALA",
    "BANYAN", "CORAL", "DELTA", "EAGLE", "FALCON", "GINGER", "HARBOUR", "INDIGO",
    "JASMINE", "KETTLE", "LANTERN", "MARIGOLD", "NUTMEG", "ORCHID", "PEACOCK",
    "QUARTZ", "RAINBOW", "SAFFRON", "TURMERIC", "UMBRELLA", "VELVET", "WALNUT",
    "YELLOW", "ZEBRA", "ANCHOR", "BAMBOO", "CANDLE", "DIAMOND", "EMERALD",
    "FOREST", "GRANITE", "HONEY", "IRON", "JUNIPER", "KOALA", "LEMON", "MEADOW",
    "NECTAR", "OLIVE", "PLANET", "QUIVER", "ROCKET", "SANDAL", "THUNDER",
    "UNICORN", "VIOLET", "WILLOW", "ZENITH",
]

_WORDS_B = [
    "STONE", "CLOUD", "FLAME", "PEARL", "BRIDGE", "MOUNTAIN", "HARVEST", "WINDOW",
    "SPARROW", "COMPASS", "LADDER", "MIRROR", "PILLAR", "SIGNAL", "TUNNEL", "VALLEY",
    "ANVIL", "BEACON", "CIRCLE", "DAGGER", "ENGINE", "FEATHER", "GLACIER", "HAMMER",
    "ISLAND", "JOURNEY", "KERNEL", "LEGEND", "MAGNET", "NEEDLE", "ORBIT", "PRISM",
    "QUILT", "RIPPLE", "SUMMIT", "TIMBER", "URCHIN", "VESSEL", "WAGON", "XENON",
    "YONDER", "ZIGZAG", "ARCHER", "BUCKLE", "CANYON", "DRIFT", "ECHO", "FURNACE",
    "GALLERY", "HORIZON", "INKWELL", "JIGSAW", "KEYSTONE", "LANTERN", "MOSAIC",
    "NOMAD", "OASIS", "PORTAL", "QUARRY", "RIDGE", "SHUTTLE", "TRELLIS", "VAULT",
    "WHISTLE",
]

# Purposes a legitimate TVS Credit outbound call can have. A caller claiming
# a purpose outside this list is itself a signal.
LEGITIMATE_PURPOSES = {
    "emi_reminder": "EMI payment reminder",
    "loan_approval": "Loan application status / approval",
    "document_request": "Pending document collection",
    "collections": "Overdue payment discussion",
    "noc_dispatch": "NOC / clearance certificate dispatch",
    "kyc_reverification": "Periodic KYC re-verification",
    "service_callback": "Customer service callback",
}

# Purposes that TVS Credit will NEVER call about. If a customer reports one of
# these as the claimed purpose, it is a scam with near-certainty and gets
# escalated regardless of code verification.
SCAM_INDICATOR_PURPOSES = {
    "otp_request": "Caller asked for an OTP",
    "remote_access": "Caller asked to install AnyDesk / TeamViewer / QuickSupport",
    "upi_pin": "Caller asked for UPI PIN or card CVV",
    "penalty_payment": "Caller demanded immediate payment to a personal account",
    "digital_arrest": "Caller claimed legal action / police / 'digital arrest'",
    "loan_processing_fee": "Caller demanded an advance processing fee",
}


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class CallSession:
    """One authenticated outbound call from TVS Credit to a customer."""
    session_id: str
    customer_id: str
    customer_masked_phone: str
    agent_id: str
    agent_name: str
    purpose: str
    phrase: str
    issued_at: float
    expires_at: float
    channel: str = "app_push"
    verified: bool = False
    verified_at: Optional[float] = None
    attempts: int = 0
    status: str = "active"          # active | verified | expired | locked

    def is_expired(self, now: Optional[float] = None) -> bool:
        return (now or time.time()) > self.expires_at

    def to_public_dict(self) -> Dict[str, Any]:
        """Representation safe to return to an officer console."""
        return {
            "session_id": self.session_id,
            "customer_id": self.customer_id,
            "customer_phone": self.customer_masked_phone,
            "agent_id": self.agent_id,
            "agent_name": self.agent_name,
            "purpose": self.purpose,
            "purpose_label": LEGITIMATE_PURPOSES.get(self.purpose, self.purpose),
            "issued_at": _iso(self.issued_at),
            "expires_at": _iso(self.expires_at),
            "seconds_remaining": max(0, int(self.expires_at - time.time())),
            "channel": self.channel,
            "status": self.status,
            "verified": self.verified,
            "attempts": self.attempts,
        }


@dataclass
class FraudReport:
    """A verification attempt that failed — i.e. a scammer identifying itself."""
    report_id: str
    reported_at: float
    customer_id: Optional[str]
    claimed_phrase: Optional[str]
    caller_number: Optional[str]
    claimed_purpose: Optional[str]
    reason: str
    severity: str                    # critical | high | medium
    had_active_session: bool

    # Populated at record time from external intelligence, when a caller
    # number is known. None when the caller withheld their number.
    fri: Optional[Dict[str, Any]] = None
    network: Optional[Dict[str, Any]] = None
    fri_report: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "report_id": self.report_id,
            "reported_at": _iso(self.reported_at),
            "customer_id": self.customer_id,
            "claimed_phrase": self.claimed_phrase,
            "caller_number": self.caller_number,
            "claimed_purpose": self.claimed_purpose,
            "reason": self.reason,
            "severity": self.severity,
            "had_active_session": self.had_active_session,
            "fri": self.fri,
            "network": self.network,
            "fri_contribution": self.fri_report,
        }


# ---------------------------------------------------------------------------
# In-memory stores
# ---------------------------------------------------------------------------
#
# Demo-scoped. In production these are Redis (sessions, TTL-native) and a
# durable event store (fraud reports, feeding the fraud-desk queue and the
# I4C / DoT Financial Fraud Risk Indicator reporting path).

_SESSIONS: Dict[str, CallSession] = {}
_SESSIONS_BY_CUSTOMER: Dict[str, List[str]] = defaultdict(list)
_FRAUD_REPORTS: List[FraudReport] = []


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _iso(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat(timespec="seconds")


def _mask_phone(phone: str) -> str:
    digits = "".join(c for c in phone if c.isdigit())
    if len(digits) < 4:
        return "****"
    return f"{'*' * (len(digits) - 4)}{digits[-4:]}"


def derive_phrase(customer_id: str, agent_id: str, session_id: str, purpose: str) -> str:
    """
    Deterministically derive the verification phrase for a session.

    The phrase is a pure function of (server secret, customer, agent, session,
    purpose). Nothing about it is stored as a secret — it can always be
    recomputed by the server and never needs to be persisted in plaintext,
    which means a database compromise does not leak live phrases.

    Returns e.g. "SAFFRON-BEACON-47"
    """
    message = f"{customer_id}|{agent_id}|{session_id}|{purpose}".encode("utf-8")
    digest = hmac.new(_SERVER_SECRET, message, hashlib.sha256).digest()

    # Slice independent byte ranges so the three components are uncorrelated.
    word_a = _WORDS_A[digest[0] % len(_WORDS_A)]
    word_b = _WORDS_B[digest[1] % len(_WORDS_B)]
    number = int.from_bytes(digest[2:4], "big") % 100

    return f"{word_a}-{word_b}-{number:02d}"


def _normalise(phrase: str) -> str:
    """
    Normalise a spoken-then-typed phrase.

    The customer heard this over a phone call and typed it into an app or an
    IVR. Tolerate case, spaces vs hyphens, and stray punctuation — but not
    the actual content. This is usability, not a weakened check: the
    comparison after normalisation is still constant-time and exact.
    """
    # Convert any run of whitespace to a separator FIRST, so "TIGER STONE 42"
    # survives; only then drop everything that is not alphanumeric or a hyphen.
    cleaned = "-".join(phrase.upper().split())
    cleaned = "".join(c for c in cleaned if c.isalnum() or c == "-")
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")


def _next_id(prefix: str) -> str:
    return f"{prefix}_{secrets.token_hex(6)}"


# ---------------------------------------------------------------------------
# Public API — outbound leg (TVS Credit initiates)
# ---------------------------------------------------------------------------

def initiate_call_session(
    customer_id: str,
    customer_phone: str,
    agent_id: str,
    agent_name: str,
    purpose: str,
    channel: str = "app_push",
) -> Dict[str, Any]:
    """
    Called the instant a TVS Credit agent (human or voicebot) dials a customer.

    Mints a session and derives the verification phrase. The phrase is pushed
    to the customer out-of-band — TVS Credit app notification, or an SMS from
    the mandated 1600-series sender — on a channel the caller does not control.

    The agent sees the phrase on their CRM screen and reads it aloud. The
    customer compares it against what arrived on their own phone.
    """
    if purpose not in LEGITIMATE_PURPOSES:
        raise ValueError(
            f"Unknown call purpose '{purpose}'. "
            f"Permitted: {sorted(LEGITIMATE_PURPOSES)}"
        )

    now = time.time()
    session_id = _next_id("tls")
    phrase = derive_phrase(customer_id, agent_id, session_id, purpose)

    session = CallSession(
        session_id=session_id,
        customer_id=customer_id,
        customer_masked_phone=_mask_phone(customer_phone),
        agent_id=agent_id,
        agent_name=agent_name,
        purpose=purpose,
        phrase=phrase,
        issued_at=now,
        expires_at=now + SESSION_TTL_SECONDS,
        channel=channel,
    )

    _SESSIONS[session_id] = session
    _SESSIONS_BY_CUSTOMER[customer_id].append(session_id)

    return {
        "session_id": session_id,
        "phrase": phrase,
        "customer_phone": session.customer_masked_phone,
        "agent_name": agent_name,
        "purpose_label": LEGITIMATE_PURPOSES[purpose],
        "expires_at": _iso(session.expires_at),
        "ttl_seconds": SESSION_TTL_SECONDS,
        "delivery_channel": channel,
        "agent_script": (
            f"Namaste, main {agent_name} TVS Credit se baat kar raha/rahi hoon. "
            f"Aapke phone par abhi ek TrustLine code aaya hoga. "
            f"Wo code hai: {phrase}. "
            f"Kripya check kijiye ki wahi code aapke TVS Credit app mein dikh raha hai. "
            f"Agar code match nahi karta, to turant call kaat dijiye — main TVS Credit se nahi hoon."
        ),
        "customer_instruction": (
            "TVS Credit will ALWAYS tell you this code. "
            "TVS Credit will NEVER ask you for it. "
            "If the caller cannot tell you the code, hang up."
        ),
    }


# ---------------------------------------------------------------------------
# Public API — inbound leg (customer verifies)
# ---------------------------------------------------------------------------

def verify_phrase(
    customer_id: str,
    claimed_phrase: str,
    caller_number: Optional[str] = None,
    claimed_purpose: Optional[str] = None,
) -> Dict[str, Any]:
    """
    The customer's side. Someone called claiming to be TVS Credit and gave a
    code; the customer types it into the TVS Credit app or the IVR.

    Four possible outcomes, in descending order of how bad they are:

      GENUINE          — phrase matches a live session. Safe to proceed.
      NO_ACTIVE_SESSION— TVS Credit is not calling this customer at all.
                         This is the strongest scam signal the system has:
                         someone is impersonating TVS Credit right now.
      PHRASE_MISMATCH  — a call is genuinely in flight but the code is wrong.
                         Either a mishearing or a scammer riding a real call
                         window. Treated as hostile until proven otherwise.
      EXPIRED / LOCKED — stale or brute-forced.
    """
    now = time.time()
    normalised = _normalise(claimed_phrase)

    # A claimed purpose that TVS Credit never calls about is decisive on its
    # own — no code check can rescue it.
    if claimed_purpose in SCAM_INDICATOR_PURPOSES:
        report = _record_fraud(
            customer_id=customer_id,
            claimed_phrase=normalised,
            caller_number=caller_number,
            claimed_purpose=claimed_purpose,
            reason=(
                f"Caller's stated purpose is one TVS Credit never calls about: "
                f"{SCAM_INDICATOR_PURPOSES[claimed_purpose]}"
            ),
            severity="critical",
            had_active_session=False,
        )
        return {
            "result": "SCAM_CONFIRMED",
            "genuine": False,
            "severity": "critical",
            "message": (
                "This is a scam call. TVS Credit never asks for OTPs, PINs, "
                "remote access, or advance payments. Disconnect immediately."
            ),
            "recommended_action": "hang_up_and_report",
            "fraud_report_id": report.report_id,
            "campaign_alert": _check_campaign(caller_number, now),
        }

    # Find live sessions for this customer.
    candidate_ids = _SESSIONS_BY_CUSTOMER.get(customer_id, [])
    live = [
        _SESSIONS[sid]
        for sid in candidate_ids
        if sid in _SESSIONS
        and _SESSIONS[sid].status == "active"
        and not _SESSIONS[sid].is_expired(now)
    ]

    if not live:
        # TVS Credit has no call in flight to this customer. Whoever is on the
        # line is not TVS Credit.
        report = _record_fraud(
            customer_id=customer_id,
            claimed_phrase=normalised,
            caller_number=caller_number,
            claimed_purpose=claimed_purpose,
            reason=(
                "Customer received a call claiming to be TVS Credit, but no "
                "TVS Credit outbound session exists for this customer."
            ),
            severity="critical",
            had_active_session=False,
        )
        return {
            "result": "NO_ACTIVE_SESSION",
            "genuine": False,
            "severity": "critical",
            "message": (
                "TVS Credit is NOT calling you right now. The person on this "
                "call is impersonating TVS Credit. Disconnect immediately and "
                "do not share any information."
            ),
            "recommended_action": "hang_up_and_report",
            "fraud_report_id": report.report_id,
            "campaign_alert": _check_campaign(caller_number, now),
        }

    # Compare against each live session in constant time.
    for session in live:
        session.attempts += 1

        if session.attempts > MAX_VERIFY_ATTEMPTS:
            session.status = "locked"
            _record_fraud(
                customer_id=customer_id,
                claimed_phrase=normalised,
                caller_number=caller_number,
                claimed_purpose=claimed_purpose,
                reason=(
                    f"Session {session.session_id} exceeded "
                    f"{MAX_VERIFY_ATTEMPTS} verification attempts — "
                    f"consistent with online guessing."
                ),
                severity="high",
                had_active_session=True,
            )
            continue

        if hmac.compare_digest(_normalise(session.phrase), normalised):
            session.verified = True
            session.verified_at = now
            session.status = "verified"     # single-use: burnt on success
            return {
                "result": "GENUINE",
                "genuine": True,
                "severity": "none",
                "message": (
                    f"Verified. This is a genuine TVS Credit call from "
                    f"{session.agent_name} regarding "
                    f"{LEGITIMATE_PURPOSES.get(session.purpose, session.purpose)}."
                ),
                "recommended_action": "safe_to_proceed",
                "session_id": session.session_id,
                "agent_name": session.agent_name,
                "purpose_label": LEGITIMATE_PURPOSES.get(session.purpose, session.purpose),
                "verified_at": _iso(now),
                "reminder": (
                    "Even on a verified call, TVS Credit will never ask for "
                    "your OTP, UPI PIN, or card CVV."
                ),
            }

    # A live session exists but the code does not match it.
    report = _record_fraud(
        customer_id=customer_id,
        claimed_phrase=normalised,
        caller_number=caller_number,
        claimed_purpose=claimed_purpose,
        reason=(
            "A genuine TVS Credit call is in progress, but the code the caller "
            "provided does not match. Possible mishearing, or a scammer calling "
            "alongside a real call window."
        ),
        severity="high",
        had_active_session=True,
    )
    return {
        "result": "PHRASE_MISMATCH",
        "genuine": False,
        "severity": "high",
        "message": (
            "That code does not match. Ask the caller to repeat it. If it still "
            "does not match, disconnect — this may not be TVS Credit."
        ),
        "recommended_action": "retry_then_hang_up",
        "attempts_remaining": max(
            0, MAX_VERIFY_ATTEMPTS - max((s.attempts for s in live), default=0)
        ),
        "fraud_report_id": report.report_id,
        "campaign_alert": _check_campaign(caller_number, now),
    }


# ---------------------------------------------------------------------------
# Fraud intelligence
# ---------------------------------------------------------------------------

def _record_fraud(
    customer_id: Optional[str],
    claimed_phrase: Optional[str],
    caller_number: Optional[str],
    claimed_purpose: Optional[str],
    reason: str,
    severity: str,
    had_active_session: bool,
) -> FraudReport:
    report = FraudReport(
        report_id=_next_id("fr"),
        reported_at=time.time(),
        customer_id=customer_id,
        claimed_phrase=claimed_phrase,
        caller_number=caller_number,
        claimed_purpose=claimed_purpose,
        reason=reason,
        severity=severity,
        had_active_session=had_active_session,
    )
    _FRAUD_REPORTS.append(report)

    # A failed verification is the moment the attacker identifies themselves.
    # Enrich it while the call is still live, and publish it outward.
    if caller_number:
        # 1. What does the country already know about this number?
        report.fri = fri.check_number(caller_number).to_dict()

        # 2. What do peer lenders already know?
        try:
            report.network = consortium.contribute(
                member_id=SELF_MEMBER_ID,
                caller_number=caller_number,
                severity=severity,
                claimed_purpose=claimed_purpose,
            )["network_view"]
        except ValueError:
            report.network = None

        # 3. Push our evidence back to DoT so the platform improves.
        report.fri_report = fri.report_fraud_signal(
            number=caller_number,
            reason=reason,
            severity=severity,
            customer_count=1,
        )

    return report


def _check_campaign(caller_number: Optional[str], now: float) -> Optional[Dict[str, Any]]:
    """
    Cluster recent failures by caller number.

    This is the asset no inbound KYC vendor can produce: the scammers
    themselves generate the signal every time a customer checks a code. One
    failed verification is an incident; several from one number inside an hour
    is a campaign in progress, and TVS Credit can warn every other customer
    that number is dialling before they pick up.
    """
    if not caller_number:
        return None

    window_start = now - CAMPAIGN_WINDOW_SECONDS
    matches = [
        r for r in _FRAUD_REPORTS
        if r.caller_number == caller_number and r.reported_at >= window_start
    ]

    if len(matches) < CAMPAIGN_ALERT_THRESHOLD:
        return None

    victims = {r.customer_id for r in matches if r.customer_id}
    return {
        "campaign_detected": True,
        "caller_number": caller_number,
        "failed_verifications": len(matches),
        "distinct_customers_targeted": len(victims),
        "window_hours": CAMPAIGN_WINDOW_SECONDS / 3600,
        "recommended_action": (
            "Block number at telecom partner, push proactive SMS warning to "
            "customers in the same pincode cluster, and file to I4C / DoT "
            "Financial Fraud Risk Indicator."
        ),
    }


def get_fraud_feed(limit: int = 50) -> Dict[str, Any]:
    """Live fraud-desk feed, newest first."""
    recent = sorted(_FRAUD_REPORTS, key=lambda r: r.reported_at, reverse=True)[:limit]

    by_number: Dict[str, int] = defaultdict(int)
    for r in _FRAUD_REPORTS:
        if r.caller_number:
            by_number[r.caller_number] += 1

    campaigns = [
        {"caller_number": num, "failed_verifications": count}
        for num, count in sorted(by_number.items(), key=lambda kv: -kv[1])
        if count >= CAMPAIGN_ALERT_THRESHOLD
    ]

    return {
        "total_reports": len(_FRAUD_REPORTS),
        "critical": sum(1 for r in _FRAUD_REPORTS if r.severity == "critical"),
        "high": sum(1 for r in _FRAUD_REPORTS if r.severity == "high"),
        "active_campaigns": campaigns,
        "reports": [r.to_dict() for r in recent],
    }


def get_session(session_id: str) -> Optional[Dict[str, Any]]:
    session = _SESSIONS.get(session_id)
    if not session:
        return None
    if session.status == "active" and session.is_expired():
        session.status = "expired"
    return session.to_public_dict()


def list_active_sessions() -> List[Dict[str, Any]]:
    now = time.time()
    out = []
    for session in _SESSIONS.values():
        if session.status == "active" and session.is_expired(now):
            session.status = "expired"
        if session.status in ("active", "verified"):
            out.append(session.to_public_dict())
    return sorted(out, key=lambda s: s["issued_at"], reverse=True)


def reset_state() -> None:
    """Test/demo helper — clears all sessions and reports."""
    _SESSIONS.clear()
    _SESSIONS_BY_CUSTOMER.clear()
    _FRAUD_REPORTS.clear()
